name: BeeAuction
version: '${version}'
main: org.djtmk.beeauction.BeeAuction
api-version: '1.21'
authors: [ djtmk ]
description: A global auction plugin for Minecraft servers
depend: [Vault]

commands:
  auction:
    description: Main command for GlobalAuction plugin
    usage: /auction <start|cancel|reload>
    aliases: [ba, ah]
    permission: auction.admin
  bid:
    description: Bid on the current auction
    usage: /bid <amount>
    permission: auction.bid
  claim:
    description: Claim items from auctions that ended while you were offline.
    usage: /claim
    permission: auction.bid

permissions:
  auction.admin:
    description: Allows access to admin commands
    default: op
  auction.bid:
    description: Allows bidding on auctions
    default: true